-- ENUMS para consistencia
create type estado_ticket as enum ('abierto', 'asignado', 'en_proceso', 'espera_repuesto', 'finalizado', 'entregado');
create type prioridad_ticket as enum ('baja', 'normal', 'alta', 'urgente');

-- PERFILES (Usuarios)
create table perfiles (
  id uuid references auth.users primary key,
  email text,
  nombre_completo text,
  rol text check (rol in ('admin', 'ventas', 'tecnico')),
  activo boolean default true
);

-- TICKETS PRINCIPALES
create table tickets (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  cliente_nombre text not null,
  cliente_contacto text,
  dispositivo_modelo text,
  falla_declarada text,
  prioridad prioridad_ticket default 'normal',
  estado estado_ticket default 'abierto',
  creado_por uuid references perfiles(id),
  asignado_a uuid references perfiles(id) -- Técnico responsable
);

-- REPORTES TÉCNICOS (AI)
create table reportes (
  id bigint generated by default as identity primary key,
  ticket_id bigint references tickets(id),
  tecnico_id uuid references perfiles(id),
  notas_brutas text, -- Lo que escribió el técnico
  reporte_ia text, -- Lo que generó Gemini
  repuestos_lista text,
  costo_reparacion decimal(10,2),
  created_at timestamptz default now()
);

-- Enable Realtime for tickets
alter publication supabase_realtime add table tickets;
